### ISSUE TITLE
How to use with docker networks

### ISSUE THREAD

**Issue by kujiy** [audreyt/ethercalc#430]
The connection to redis will be lost when I add `net: my-network` into the default `docker-compose.yml`.
- docker-compose.yml
  
  ```
  ethercalc:
  image: audreyt/ethercalc
  ports:
    - "80:8000"
  links:
    - redis
  restart: always
  net: my-network
  redis:
  image: redis:latest
  volumes:
    - /var/lib/redis:/data
  command: redis-server --appendonly yes
  restart: always
  net: my-network
  ```
- docker log
  
  ```
  ethercalc_1  | ethercalc-0 Starting backend using webworker-threads
  ethercalc_1  | ethercalc-0 Cross-Origin Resource Sharing (CORS) enabled.
  ethercalc_1  | ethercalc-0 Express server listening on port 8000 in development mode
  ethercalc_1  | ethercalc-0 Zappa 0.5.0 "You can't do that on stage anymore" orchestrating the show
  ethercalc_1  | ethercalc-0 [Error: Redis connection to  failed - connect ECONNREFUSED]
  ethercalc_1  | ethercalc-0 ==> Falling back to JSON storage: //dump.json
  ```

It works well when I type `docker network connect my-network` after `docker-compose up` but I'd like to reduce the procedure. Honestly I'd like to use docker-compose v2 but the same problem happened when tried it with docker-network.

Does anybody give me an advice?

**Comment by eddyparkinson** [comment]
@kujiy are you still looking for a solution?

I notice that @qinshulei changed the redis setting.

```
  links:
    - redis:redis

```
does this fix the issue?

also when Redis is not running, I get 
"Redis connection to localhost:6379 failed"

rather than:
"Redis connection to  failed"

**Comment by rocketnova** [comment]
I think this might be because https://github.com/audreyt/ethercalc/blob/master/Dockerfile#L9 and the fact that link environment variables have been deprecated: https://docs.docker.com/compose/link-env-deprecated/

When I was running into this, I found two solutions. (1) You can write your own Dockerfile and replace line 9 with: `CMD ["sh", "-c", "REDIS_HOST=redis start -x `which ethercalc` -- --cors && pm2 logs"]`

(2) You can use audreyt/ethercalc, but modify your docker-compose.yml by manually setting the necessary environment variables:

````
ports:
      - 80:8000
    environment:
      - REDIS_PORT_6379_TCP_ADDR=redis
      - REDIS_PORT_6379_TCP_PORT=6379
````

**Comment by kujiy** [comment]
Hi @rocketnova 

I'm sorry for my late reply. I don't know why but somehow it has started to work without fixing my compose.yml. Perhaps I upgraded docker to 1.13?

JYI, here is my docker-compose.yml

```
version: '2' 

services:
  ethercalc:
    depends_on:
      - redis
    image: audreyt/ethercalc
    container_name: ethercalc
    hostname: ethercalc
    ports:
      - 32000:8000
    links:
      - redis:redis
    restart: always
    volumes:
      - /kc:/kc
      - /etc/localtime:/etc/localtime:ro
    networks:
      - MYNETWORK

  redis:
    image: redis:latest
    container_name: ethercalc_redis
    volumes:
      - /srv/ethercalc/redis/var/lib/redia:/data
    command: redis-server --appendonly yes 
    restart: always
    networks:
      - MYNETWORK

networks:
  MYNETWORK:
      external: true
```

Anyway it seemed for the time to close this issue. Thank you.

**Comment by kujiy** [comment]
# This is my docker-compose.yml with @rocketnova suggestion

```yml
version: '2'

services:
  ethercalc:
    depends_on:
      - redis
    image: audreyt/ethercalc
    container_name: ethercalc
    hostname: ethercalc
    ports:
      - 80:8000
    links:
      - redis:redis
    restart: always
    environment:
      - REDIS_PORT_6379_TCP_ADDR=redis
      -  REDIS_PORT_6379_TCP_PORT=6379
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - MYNETWORK

  redis:
    image: redis:latest
    container_name: ethercalc_redis
    volumes:
      - /srv/ethercalc/redis/var/lib/redia:/data
    command: redis-server --appendonly yes
    restart: always
    networks:
      - MYNETWORK

networks:
  MYNETWORK:
      external: true
```

NOTE: You MUST define BOTH system variables below.
```
      - REDIS_PORT_6379_TCP_ADDR=redis
      - REDIS_PORT_6379_TCP_PORT=6379
```

You will get the error below when you define only `REDIS_PORT_6379_TCP_ADDR`.
```
ethercalc    | PM2 App [ethercalc] with id [0] and pid [40], exited with code [255] via signal [SIGINT]
ethercalc    | PM2 Starting execution sequence in -fork mode- for app name:ethercalc id:0
ethercalc    | PM2 App name:ethercalc id:0 online
ethercalc    | ethercalc-0 Please connect to: http://ethercalc:8000/
ethercalc    | ethercalc-0 Starting backend using webworker-threads
ethercalc    | ethercalc-0 Cross-Origin Resource Sharing (CORS) enabled.
ethercalc    | ethercalc-0 Express server listening on port 8000 in development mode
ethercalc    | ethercalc-0 Zappa 0.5.0 "You can't do that on stage anymore" orchestrating the show
ethercalc    | ethercalc-0 [Error: Redis connection to  failed - connect ECONNREFUSED]
ethercalc    | ethercalc-0 ==> Falling back to JSON storage: //dump.json
ethercalc    | ethercalc-0 join [log-test_formdata] [user-0.2740245803858059]
ethercalc    | ethercalc-0 join [log-test] [user-0.2740245803858059]
```
